#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: MIT-0

connect_flow = {"modules": [{"id": "640e0a9a-361d-42bf-81f4-6f11457951ce", "type": "SetLoggingBehavior", "branches": [
    {"condition": "Success", "transition": "101cd9ec-19eb-4fed-a395-df0c70d777dd"}],
                               "parameters": [{"name": "LoggingBehavior", "value": "Enable"}],
                               "metadata": {"position": {"x": 157, "y": 12}}},
                              {"id": "101cd9ec-19eb-4fed-a395-df0c70d777dd", "type": "GetUserInput", "branches": [
                                  {"condition": "Evaluate", "conditionType": "Equals", "conditionValue": "Auth",
                                   "transition": "029a95d9-e2c5-46f2-9a53-dbc93077f922"},
                                  {"condition": "NoMatch", "transition": "029a95d9-e2c5-46f2-9a53-dbc93077f922"},
                                  {"condition": "Error", "transition": "029a95d9-e2c5-46f2-9a53-dbc93077f922"}],
                               "parameters": [{"name": "Text",
                                               "value": "Hi, I am your virtual healthcare assistant. Is this Jane Doe?",
                                               "namespace": None}, {"name": "TextToSpeechType", "value": "text"},
                                              {"name": "BotName", "value": "Drug_Reminder_Bot"},
                                              {"name": "BotAlias", "value": "live"},
                                              {"name": "BotRegion", "value": "us-east-1"}],
                               "metadata": {"position": {"x": 142, "y": 299}, "conditionMetadata": [
                                   {"id": "cd34126a-99ac-48c3-8e12-a0a5f47b1c54", "value": "Auth"}],
                                            "useDynamic": False, "dynamicMetadata": {}, "useLexBotDropdown": True,
                                            "useDynamicLexBotArn": False, "lexV2BotName": "Drug_Reminder_Bot"},
                               "target": "Lex"}, {"id": "029a95d9-e2c5-46f2-9a53-dbc93077f922", "type": "GetUserInput",
                                                  "branches": [{"condition": "Evaluate", "conditionType": "Equals",
                                                                "conditionValue": "Dose_Appearance",
                                                                "transition": "8c076ca6-9d04-4a6f-b6b9-82bb3c7c9213"},
                                                               {"condition": "NoMatch",
                                                                "transition": "8c076ca6-9d04-4a6f-b6b9-82bb3c7c9213"},
                                                               {"condition": "Error",
                                                                "transition": "8c076ca6-9d04-4a6f-b6b9-82bb3c7c9213"}],
                                                  "parameters": [{"name": "Text",
                                                                  "value": "Thanks. I am calling you about your afternoon medication. Have you taken your medication yet?",
                                                                  "namespace": None},
                                                                 {"name": "TextToSpeechType", "value": "text"},
                                                                 {"name": "BotName", "value": "Drug_Reminder_Bot"},
                                                                 {"name": "BotAlias", "value": "live"},
                                                                 {"name": "BotRegion", "value": "us-east-1"}],
                                                  "metadata": {"position": {"x": 383, "y": 301}, "conditionMetadata": [
                                                      {"id": "78c17d5c-8571-4233-baa8-adf809a73405",
                                                       "value": "Dose_Appearance"}], "useDynamic": False,
                                                               "dynamicMetadata": {}, "useLexBotDropdown": True,
                                                               "useDynamicLexBotArn": False,
                                                               "lexV2BotName": "Drug_Reminder_Bot"}, "target": "Lex"},
                              {"id": "e4a222fe-eefa-48e9-ae65-6a6c60c455bb", "type": "Disconnect", "branches": [],
                               "parameters": [], "metadata": {"position": {"x": 1730, "y": 596}}},
                              {"id": "8c076ca6-9d04-4a6f-b6b9-82bb3c7c9213", "type": "GetUserInput", "branches": [
                                  {"condition": "Evaluate", "conditionType": "Equals",
                                   "conditionValue": "Dose_Quantity",
                                   "transition": "0b2ac510-f213-4c3f-93ae-29b9d48a6a9e"},
                                  {"condition": "NoMatch", "transition": "0b2ac510-f213-4c3f-93ae-29b9d48a6a9e"},
                                  {"condition": "Error", "transition": "0b2ac510-f213-4c3f-93ae-29b9d48a6a9e"}],
                               "parameters": [{"name": "Text",
                                               "value": "It is a medium, round, pink tablet, and it comes in a white box.",
                                               "namespace": None}, {"name": "TextToSpeechType", "value": "text"},
                                              {"name": "BotName", "value": "Drug_Reminder_Bot"},
                                              {"name": "BotAlias", "value": "live"},
                                              {"name": "BotRegion", "value": "us-east-1"}],
                               "metadata": {"position": {"x": 620, "y": 296}, "conditionMetadata": [
                                   {"id": "2ae1ff4d-17ba-4ac4-9590-89319460933a", "value": "Dose_Quantity"}],
                                            "useDynamic": False, "dynamicMetadata": {}, "useLexBotDropdown": True,
                                            "useDynamicLexBotArn": False, "lexV2BotName": "Drug_Reminder_Bot"},
                               "target": "Lex"}, {"id": "680ef637-3b84-47dd-a2fc-cabfa8ca1789", "type": "PlayPrompt",
                                                  "branches": [{"condition": "Success",
                                                                "transition": "e4a222fe-eefa-48e9-ae65-6a6c60c455bb"}],
                                                  "parameters": [{"name": "Text", "value": "Thanks. Have a great day.",
                                                                  "namespace": None},
                                                                 {"name": "TextToSpeechType", "value": "text"}],
                                                  "metadata": {"position": {"x": 1654, "y": 357}, "useDynamic": False}},
                              {"id": "5c06e0d7-a3c6-4341-b60f-c3694f6d86e2", "type": "GetUserInput", "branches": [
                                  {"condition": "Evaluate", "conditionType": "Equals", "conditionValue": "Close_Intent",
                                   "transition": "680ef637-3b84-47dd-a2fc-cabfa8ca1789"},
                                  {"condition": "NoMatch", "transition": "680ef637-3b84-47dd-a2fc-cabfa8ca1789"},
                                  {"condition": "Error", "transition": "680ef637-3b84-47dd-a2fc-cabfa8ca1789"}],
                               "parameters": [{"name": "Text",
                                               "value": "Your MRI scan is scheduled for May 15th at 9 AM. Is there anything else I can help you with?",
                                               "namespace": None}, {"name": "TextToSpeechType", "value": "text"},
                                              {"name": "BotName", "value": "Drug_Reminder_Bot"},
                                              {"name": "BotAlias", "value": "live"},
                                              {"name": "BotRegion", "value": "us-east-1"}],
                               "metadata": {"position": {"x": 1368, "y": 310}, "conditionMetadata": [
                                   {"id": "6bee5b2a-3a72-49a1-a8fa-c5f3417921b7", "value": "Close_Intent"}],
                                            "useDynamic": False, "dynamicMetadata": {}, "useLexBotDropdown": True,
                                            "useDynamicLexBotArn": False, "lexV2BotName": "Drug_Reminder_Bot"},
                               "target": "Lex"}, {"id": "0b2ac510-f213-4c3f-93ae-29b9d48a6a9e", "type": "GetUserInput",
                                                  "branches": [{"condition": "Evaluate", "conditionType": "Equals",
                                                                "conditionValue": "Dose_Confirm",
                                                                "transition": "90b6b0a2-b7a5-4e93-9577-654ceb85047f"},
                                                               {"condition": "NoMatch",
                                                                "transition": "90b6b0a2-b7a5-4e93-9577-654ceb85047f"},
                                                               {"condition": "Error",
                                                                "transition": "90b6b0a2-b7a5-4e93-9577-654ceb85047f"}],
                                                  "parameters": [{"name": "Text",
                                                                  "value": "You need to take 1 dose now. Let me know once you’ve taken it",
                                                                  "namespace": None},
                                                                 {"name": "TextToSpeechType", "value": "text"},
                                                                 {"name": "BotName", "value": "Drug_Reminder_Bot"},
                                                                 {"name": "BotAlias", "value": "live"},
                                                                 {"name": "BotRegion", "value": "us-east-1"}],
                                                  "metadata": {"position": {"x": 843, "y": 293}, "conditionMetadata": [
                                                      {"id": "2e1777b2-d4b6-4845-ac53-fef66cd93c92",
                                                       "value": "Dose_Confirm"}], "useDynamic": False,
                                                               "dynamicMetadata": {}, "useLexBotDropdown": True,
                                                               "useDynamicLexBotArn": False,
                                                               "lexV2BotName": "Drug_Reminder_Bot"}, "target": "Lex"},
                              {"id": "90b6b0a2-b7a5-4e93-9577-654ceb85047f", "type": "GetUserInput", "branches": [
                                  {"condition": "Evaluate", "conditionType": "Equals", "conditionValue": "MRI_Scan",
                                   "transition": "5c06e0d7-a3c6-4341-b60f-c3694f6d86e2"},
                                  {"condition": "NoMatch", "transition": "5c06e0d7-a3c6-4341-b60f-c3694f6d86e2"},
                                  {"condition": "Error", "transition": "5c06e0d7-a3c6-4341-b60f-c3694f6d86e2"}],
                               "parameters": [
                                   {"name": "Text", "value": "Okay.  Is there anything else I can help you with?",
                                    "namespace": None}, {"name": "TextToSpeechType", "value": "text"},
                                   {"name": "BotName", "value": "Drug_Reminder_Bot"},
                                   {"name": "BotAlias", "value": "live"}, {"name": "BotRegion", "value": "us-east-1"}],
                               "metadata": {"position": {"x": 1088, "y": 292}, "conditionMetadata": [
                                   {"id": "67dc98e5-688e-4530-9395-e524fb89eaa9", "value": "MRI_Scan"}],
                                            "useDynamic": False, "dynamicMetadata": {}, "useLexBotDropdown": True,
                                            "useDynamicLexBotArn": False, "lexV2BotName": "Drug_Reminder_Bot"},
                               "target": "Lex"}], "version": "1", "type": "contactFlow",
                  "start": "640e0a9a-361d-42bf-81f4-6f11457951ce",
                  "metadata": {"entryPointPosition": {"x": 15, "y": 20}, "snapToGrid": False, "name": "drug_reminder",
                               "description": None, "type": "contactFlow", "status": "published",
                               "hash": "552919265434494e0b11039d5bd70b7b41f2c68b7813cd6d55c85b4262c7b8bf"}}
